### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#17]
### TODOs
 
- [x] Update metadata according to https://central.sonatype.org/pages/requirements.html
- [x] Set up GPG signing usign https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F
- [x] Make sure profile still allows GH Actions to work
- [x] Make sure snapshots are signed
- [x] Make sure snapshots are pushed to OSSRH
- [x] Write back after a success to https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263 so that OSSRH flips the switch

### Links

https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263 for tracking

https://wiki.eclipse.org/IT_Infrastructure_Doc#Publish_to_Maven_Central checklist

**Comment by berezovskyi** [comment]
Instructions https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-62358

**Comment by berezovskyi** [comment]
And eclipse specific instructions https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263

**Comment by berezovskyi** [comment]
GPG signing success https://repo.eclipse.org/content/repositories/lyo-snapshots/org/eclipse/lyo/oslc4j/core/oslc4j-core/4.0.0-SNAPSHOT/

**Comment by berezovskyi** [comment]
Requested Eclipse help to ensure OSSRH snapshots are deployed correctly https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263

**Comment by berezovskyi** [comment]
So we hit a snag, trs-server had a duplicate definition of the javadoc/sources packaging and according to the Eclipse policy, Nexus rejected an attempt to deploy a single javadoc/source jar twice. See https://stackoverflow.com/questions/4251488/maven-release-plugin-fails-source-artifacts-getting-deployed-twice for reason why (treat this comment as an incident report).

Log:

```
[INFO] Lyo :: _Parent ..................................... SUCCESS [  1.102 s]
[INFO] Lyo :: Core :: _Parent ............................. SUCCESS [  0.793 s]
[INFO] Lyo :: Core :: OSLC ................................ SUCCESS [  6.104 s]
[INFO] Lyo :: Core :: Query ............................... SUCCESS [  4.919 s]
[INFO] Lyo :: Core :: Jena Provider ....................... SUCCESS [  2.980 s]
[INFO] Lyo :: Core :: TRS ................................. SUCCESS [  2.654 s]
[INFO] Lyo :: Core :: JSON4J Provider (legacy) ............ SUCCESS [  3.603 s]
[INFO] Lyo :: Core :: Utilities ........................... SUCCESS [  2.369 s]
[INFO] Lyo :: Core :: SHACL ............................... SUCCESS [  2.404 s]
[INFO] Lyo :: Domains ..................................... SUCCESS [  1.031 s]
[INFO] Lyo :: Client :: _Parent ........................... SUCCESS [  0.356 s]
[INFO] Lyo :: Client :: Base .............................. SUCCESS [  0.712 s]
[INFO] Lyo :: Client :: OSLC JAX-RS 2.0 (new) ............. SUCCESS [  4.574 s]
[INFO] Lyo :: Client :: Resources (legacy) ................ SUCCESS [  0.954 s]
[INFO] Lyo :: Client :: OSLC Wink (legacy) ................ SUCCESS [  6.579 s]
[INFO] Lyo :: OAuth :: _Parent ............................ SUCCESS [  1.044 s]
[INFO] Lyo :: OAuth :: Core ............................... SUCCESS [  3.180 s]
[INFO] Lyo :: OAuth :: Consumer Store ..................... SUCCESS [  2.159 s]
[INFO] Lyo :: OAuth :: Webapp ............................. SUCCESS [  2.098 s]
[INFO] Lyo :: Misc :: Wink registration (legacy) .......... SUCCESS [  2.069 s]
[INFO] Lyo :: Misc :: Registry ............................ SUCCESS [  2.426 s]
[INFO] Lyo :: TRS :: Server ............................... FAILURE [  3.592 s]
[INFO] Lyo :: TRS :: Client :: _Parent .................... SKIPPED
[INFO] Lyo :: TRS :: Client :: Client library ............. SKIPPED
[INFO] Lyo :: TRS :: Client :: MQTT source ................ SKIPPED
[INFO] Lyo :: Store :: _Parent ............................ SKIPPED
[INFO] Lyo :: Store :: Core ............................... SKIPPED
[INFO] Lyo :: Validation .................................. SKIPPED
```

After fixing the problem redeploy fails even earlier and things like `--fail-at-end` do not help:

```
[INFO] Lyo :: _Parent ..................................... FAILURE [  0.955 s]
[INFO] Lyo :: Core :: _Parent ............................. SKIPPED
[INFO] Lyo :: Core :: OSLC ................................ SKIPPED
[INFO] Lyo :: Core :: Query ............................... SKIPPED
[INFO] Lyo :: Core :: Jena Provider ....................... SKIPPED
[INFO] Lyo :: Core :: TRS ................................. SKIPPED
[INFO] Lyo :: Core :: JSON4J Provider (legacy) ............ SKIPPED
[INFO] Lyo :: Core :: Utilities ........................... SKIPPED
[INFO] Lyo :: Core :: SHACL ............................... SKIPPED
[INFO] Lyo :: Domains ..................................... SKIPPED
[INFO] Lyo :: Client :: _Parent ........................... SKIPPED
[INFO] Lyo :: Client :: Base .............................. SKIPPED
[INFO] Lyo :: Client :: OSLC JAX-RS 2.0 (new) ............. SKIPPED
[INFO] Lyo :: Client :: Resources (legacy) ................ SKIPPED
[INFO] Lyo :: Client :: OSLC Wink (legacy) ................ SKIPPED
[INFO] Lyo :: OAuth :: _Parent ............................ SKIPPED
[INFO] Lyo :: OAuth :: Core ............................... SKIPPED
[INFO] Lyo :: OAuth :: Consumer Store ..................... SKIPPED
[INFO] Lyo :: OAuth :: Webapp ............................. SKIPPED
[INFO] Lyo :: Misc :: Wink registration (legacy) .......... SKIPPED
[INFO] Lyo :: Misc :: Registry ............................ SKIPPED
[INFO] Lyo :: TRS :: Server ............................... SKIPPED
[INFO] Lyo :: TRS :: Client :: _Parent .................... SKIPPED
[INFO] Lyo :: TRS :: Client :: Client library ............. SKIPPED
[INFO] Lyo :: TRS :: Client :: MQTT source ................ SKIPPED
[INFO] Lyo :: Store :: _Parent ............................ SKIPPED
[INFO] Lyo :: Store :: Core ............................... SKIPPED
[INFO] Lyo :: Validation .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
```

Options:

1. Disable deploy to OSSRH; Add https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#skip to all POMs except TRS Client, Store, and Validation; Redeploy; Disable Eclipse Deploy; enable OSSRH deploy; Rollback skip commit.
1. Ask Eclipse admin to remove 4.0.0.M2 artifacts from Eclipse.
1. Ignore Eclipse repo altogether.
1. Skip 4.0.0.RC and release 4.0.0.RC2.

**Comment by berezovskyi** [comment]
I decided to go for (3) and in case of success, go for (2). But we are just getting really "lucky", Sonatype decided to open a service window https://status.maven.org/incidents/97rb5zwfllx6

**Comment by berezovskyi** [comment]
Update: the deploy to OSSRH was successful and I tried to "close" the repository for release but we failed a few POM file quality checks. 

These are the updates made to address the problems: https://github.com/eclipse/lyo/commit/8b324bba946eb6de2b50eee20701282c0c28ecb2

**Comment by berezovskyi** [comment]
Another update: everything seems to be fine from the tech pov this time but we failed again:

> Invalid POM: /org/eclipse/lyo/lyo-parent/4.0.0.RC/lyo-parent-4.0.0.RC.pom: Project description missing

I will be adding the following statement to the POM file:

> The Eclipse Lyo project is focused on providing an SDK to enable adoption of OSLC specifications. OSLC (Open Services for Lifecycle Collaboration) is an open community dedicated to reducing barriers for lifecycle tool integration. The community authors specifications for exposing lifecycle artifacts through uniform (REST) interfaces and relying on Internet and Linked Data standards.

**Comment by berezovskyi** [comment]
All Maven Central checks passed successfully and OSSRH to Central sync was requested in https://issues.sonatype.org/browse/OSSRH-62358

A request to purge 4.0.0.RC from Eclipse lyo-releases was filed under https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263

I am not reverting to 4.0.0-SNAPSHOT on master till the issue above is resolved and to that effect I disabled the build https://ci.eclipse.org/lyo/view/1Enabled/job/lyo-monorepo/ completely to avoid accidental re-deploy attempt.

Forum post for 4.0.0.RC is prepared and will be published hopefully tomorrow when the Eclipse deploy is fixed and Maven Central deploy is synced.

I will close the ticket when I can update 4.0.0-SNAPSHOT to 4.0.0.RC and remove Eclipse repos in one of the adaptors and run it without problems.

**Comment by berezovskyi** [comment]
All right, Eclipse deploy has succeeded as well now: https://repo.eclipse.org/content/repositories/lyo-releases/org/eclipse/lyo/oslc4j/core/oslc4j-core/4.0.0.RC/

URLs to monitor for Central:

- https://search.maven.org/search?q=org.eclipse.lyo
- https://repo1.maven.org/maven2/org/eclipse/lyo

**Comment by berezovskyi** [comment]
RefImpl has been updated to 4.0.0.RC but not yet from Central: https://github.com/oslc-op/refimpl/pull/24

**Comment by berezovskyi** [comment]
https://repo1.maven.org/maven2/org/eclipse/lyo/
